---
- name: make sure saml dependency packages are installed
  action: apt pkg={{item}} state=installed
  with_items:
    - memcached
    - xmlsec1
    - swig

- name: create directories
  action: file path=/etc/ckan/saml2/ state=directory mode=0755

- name: create pki directory
  action: file path=/etc/ckan/saml2/pki state=directory mode=0750

- name: copy all needed files
  action: copy src=etc/ckan/saml2/ dest=/etc/ckan/saml2/

- name: template all needed files
  action: template src=etc/ckan/{{item}} dest=/etc/ckan/{{item}}
  with_items:
    - saml2/pki/mycert.pem
    - saml2/pki/mykey.pem
    - who.ini

- name: Downloads idp metadata
  get_url:
    url: "{{ saml2_idp_metadata_url }}"
    dest: /etc/ckan/saml2/idp.xml
    mode: 0644
