---
- name: create directories
  action: file path=/etc/ckan/saml2/ state=directory mode=0755 owner=root group=www-data

- name: create pki directory
  action: file path=/etc/ckan/saml2/pki state=directory mode=0750 owner=root group=www-data

- name: create attributemaps directory
  action: file path=/etc/ckan/saml2/attributemaps state=directory mode=0755 owner=root group=www-data

# TODO remove me after https://github.com/GSA/datagov-deploy/issues/1968
# Cleanup fallout #1968
- name: copy all needed files
  file: dest=/etc/ckan/saml2/{{ item }} state=absent
  with_items:
    - basic.py
    - saml_uri.py
  notify: reload apache2

# TODO configuration files should live in the application repo
- name: copy all needed files
  action: copy src=etc/ckan/saml2/{{ inventory_saml_type }}/attributemaps dest=/etc/ckan/saml2/attributemaps mode=0644 owner=root group=www-data
  notify: reload apache2

- name: template all cert files
  action: template src=etc/ckan/{{ item }} dest=/etc/ckan/{{ item }} mode=0640 owner=root group=www-data
  with_items:
    - saml2/pki/mycert.pem
    - saml2/pki/mykey.pem
  notify: reload apache2

- name: template who.ini file
  action: template src=etc/ckan/{{ inventory_saml_type }}/who.ini.j2 dest=/etc/ckan/who.ini mode=0640 owner=root group=www-data
  notify: reload apache2

- name: Downloads idp metadata
  get_url:
    url: "{{ saml2_idp_metadata_url }}"
    dest: /etc/ckan/saml2/idp.xml
    mode: 0644
  notify: reload apache2
