---
- name: prepare
  hosts: all
  become: true
  gather_facts: false
  vars:
    js_files:
      - dest: /usr/lib/ckan/src/ckanext-datagovtheme/ckanext/datagovtheme/fanstatic_library/scripts/tracking.js
        content: |
          ...
          var url = $(this).closest('a').attr('href');
          $.ajax({url : '/_tracking',
            data : {url:url, type:'resource'},
          ...
      - dest: /usr/lib/ckan/src/ckan/ckan/public/base/javascript/tracking.js
        content: |
          ...
            url = url.replace(/\/*$/, '');
            $.ajax({url : $('body').data('site-root') + '_tracking',
                    type : 'POST',
          ...
            var url = $(e.target).closest('a').attr('href');
            $.ajax({url : $('body').data('site-root') + '_tracking',
                    data : {url:url, type:'resource'},
          ...
      - dest: /usr/lib/ckan/src/ckan/ckan/public/base/javascript/tracking.min.js
        content: ;$.ajax({url:$('body').data('site-root')+'_tracking',type:'POST',...;$.ajax({url:$('body').data('site-root')+'_tracking',data:...

  pre_tasks:
  - name: make direcotries
    file:
      path: "{{ item.dest | dirname }}"
      state: directory
      recurse: yes
    with_items: "{{ js_files }}"

  - name: create sample js files
    copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      mode: "0644"
    with_items: "{{ js_files }}"
