---
- name: Converge
  hosts: all
  roles:
    - role: ckan-app
      vars:
        catalog_app_type: worker
        catalog_ckan_email_from: no-reply@data.gov
        catalog_ckan_worker_type: main_worker
        catalog_harvest_enable_harvest_report: true
        ckan_email_test_server_enabled: true
