---
# catalog
catalog_ckan_apache_server_name: "{{ catalog_host_public }}"
catalog_ckan_app_version: fcs
catalog_ckan_archiver_process_count: 3
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_email_from: "{{ default_email_from }}"
catalog_ckan_harvest_fetch_process_count: 4
catalog_ckan_plugins_additional: [saml2]
catalog_ckan_qa_update_process_count: 5
catalog_ckan_readwrite_configuration: readonly
catalog_ckan_redis_host: catalog-harvester1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_redis_password: "{{ redis_password }}"
catalog_ckan_fgdc2iso_host: catalog-fgdc2iso1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_saml2_enabled: true
catalog_ckan_service_url: https://{{ catalog_host_public }}
catalog_ckan_admin_service_url: https://{{ catalog_host_admin }}
catalog_ckan_who_ini_path: "etc_ckan_who.saml2.ini.j2"
catalog_ckan_solr_port: "8983"
catalog_ckan_solr_host: datagov-solr1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_wsgi_processes: 6
catalog_pycsw_db_host: "{{ vault_catalog_pycsw_db_host }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: "{{ vault_catalog_pycsw_db_user }}"

# catalog-next
catalog_next_ckan_db_name: "{{ vault_catalog_next_ckan_db_name }}"
catalog_next_ckan_db_pass: "{{ vault_catalog_next_ckan_db_pass }}"
catalog_next_ckan_db_primary_host: "{{ vault_catalog_next_ckan_db_primary_host }}"
catalog_next_ckan_db_replica_a_host: "{{ vault_catalog_next_ckan_db_replica_a_host }}"
catalog_next_ckan_db_replica_b_host: "{{ vault_catalog_next_ckan_db_replica_b_host }}"
catalog_next_ckan_db_user: "{{ vault_catalog_next_ckan_db_user }}"
catalog_next_ckan_envs: |
  {{ newrelic_app_envs }}
catalog_next_ckan_instance_secret: "{{ vault_catalog_next_ckan_instance_secret }}"
catalog_next_ckan_instance_uuid: 5ab5625f-4ec5-435b-a725-55eaa36d264b
catalog_next_ckan_postgresql_admin_host: "{{ vault_catalog_next_ckan_postgresql_admin_host }}"
catalog_next_ckan_postgresql_admin_password: "{{ vault_catalog_next_ckan_postgresql_admin_password }}"
catalog_next_ckan_postgresql_admin_user: "{{ vault_catalog_next_ckan_postgresql_admin_user }}"
catalog_next_ckan_production_ini_template: catalog-next/etc_ckan_production.ini.j2
catalog_next_ckan_redis_host: redis1p.prod-ocsit.bsp.gsa.gov
catalog_next_ckan_redis_password: "{{ redis_password }}"
catalog_next_ckan_redis_url: redis://:{{ catalog_next_ckan_redis_password }}@{{ catalog_next_ckan_redis_host }}:6379/0
catalog_next_ckan_solr_a_host: datagov-solr1p-v2.prod-ocsit.bsp.gsa.gov
catalog_next_ckan_solr_b_host: datagov-solr2p-v2.prod-ocsit.bsp.gsa.gov
catalog_next_ckan_solr_primary_host: datagov-solrm1p-v2.prod-ocsit.bsp.gsa.gov
catalog_next_ckan_token_dat: "{{ vault_catalog_next_ckan_token_dat }}"
catalog_next_ckan_who_ini_secret: "{{ vault_catalog_next_ckan_who_ini_secret }}"
catalog_next_ckan_saml2_enabled: true
catalog_next_ckan_who_ini_path: "etc_ckan_who.default.ini.j2"
catalog_next_saml2_sp_public_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIGQDCCBCgCCQCQZGY2iUS9zjANBgkqhkiG9w0BAQsFADCB4TELMAkGA1UEBhMC
  VVMxHTAbBgNVBAgMFERpc3RyaWN0IG9mIENvbHVtYmlhMRMwEQYDVQQHDApXYXNo
  aW5ndG9uMSgwJgYDVQQKDB9HZW5lcmFsIFNlcnZpY2VzIEFkbWluaXN0cmF0aW9u
  MSowKAYDVQQLDCFUZWNobm9sb2d5IFRyYW5zZm9ybWF0aW9uIFNlcnZpY2UxIjAg
  BgkqhkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3YxJDAiBgNVBAMMG2FkbWlu
  LWNhdGFsb2ctbmV4dC5kYXRhLmdvdjAeFw0yMTAzMjIxNDE4MDNaFw0yMzAzMjIx
  NDE4MDNaMIHhMQswCQYDVQQGEwJVUzEdMBsGA1UECAwURGlzdHJpY3Qgb2YgQ29s
  dW1iaWExEzARBgNVBAcMCldhc2hpbmd0b24xKDAmBgNVBAoMH0dlbmVyYWwgU2Vy
  dmljZXMgQWRtaW5pc3RyYXRpb24xKjAoBgNVBAsMIVRlY2hub2xvZ3kgVHJhbnNm
  b3JtYXRpb24gU2VydmljZTEiMCAGCSqGSIb3DQEJARYTZGF0YWdvdmhlbHBAZ3Nh
  LmdvdjEkMCIGA1UEAwwbYWRtaW4tY2F0YWxvZy1uZXh0LmRhdGEuZ292MIICIjAN
  BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5wnO6dc1WDCFwqtNS5KkcRGjr/B+
  QLTny6n1Vdn3uqkDyYH2DPT43RQk49UdAL80Pj3XxXODzANtpVceouWKJxPWsttv
  4RmNSmvGpjkQ7wJ3zQl+NP0MNlAsUcQH3jKIaTJn5smq2VFmx9uMRRDTYRKLCzXd
  tfP78hNasUixTJSj997fYtmTxth4bRtxTiie+RSDiMpGcYWBXrOGWP00S0XEXhzs
  qU3ngFi/0MNWeHmFGpYq+KId71e6lTFOpHEymYqkFfK3cvioRtR2mpKY/ePM2oPj
  v/CHro6e5wV88D3I1q5OVQ9Yqp9FGIyMVKULYnGVC1M7wlZae3TaUefWzoVNqThx
  fUbY12Z0oGVyiV/zr5cdG3LKP/ehn2HReuFB5odnFUgoHczIgV/IZdethjEqk0xa
  cePkpcX1Ewh5eoQu6em20X4krd+HsyHbmcYjMqZAihwY4xk12D2s5fZ5zx+x/Du0
  ibRy7HXGCSdGsCtXmseAEoI4AAqLvOh2vXytP+9c0ZiYCVgWJCn4o0t4/r5aw9Pe
  4sHqgX4YSF5hIjx+vcT+7gFRc62/vEkuUJ1X7vcu3+FHJB84s/1JngasfM7abP5a
  ACjmYjWzswmDvw6DgqHyKLVs8kfEgeXe6mnrjMVA+S4RikwjGpr+DS3JD73K13+S
  PossCAIU1kFHXkUCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAqkbCO5CqAXh6Is1V
  3oolwI3GK8rmMtDCEhv0WQn2uOcyiLe9gE35fObtAuDG+Y4OFa6RkMsSbEXPjvur
  ghmgksQ3jalMMNobeRcFOOWC9IEbSASyfRUyJuVs5R2WTyAMsxfhU9ZB6vl+VdOu
  ijEOpcIdSwxQ1b5aMln6j8SBeuXGwHo47sq7ax5rVovnuZX27oHK5JAopAQ0HWqW
  N3m2paplI14rayrHT1p8KAlcPq6t3p/3iriwbYxpXFVB4t6ODoewD8qjskdWQwAO
  lGv+z4J7/4VhwTMqACu4GILrUfaAWTaVawGeCNL/CdboYxHHIB5blUUgu3VH5ULy
  34uNTDcXyMhs3/GC8AHaIDztXsxPgcwOITeJjXhUsfXp5HF0D0Fuj3IGa/dx/gcO
  bO/AwllK+CQHhVDlKSF/5iUI0qMm13Rq1xslJGrjJ/BQyfUMvVMffPssUz3a/3XM
  MGsPAMufXPLtLbRdO4MBcVboBJhr4BeI0uaUfTvl1zcvAoy5g6bxgBhzN3tl+XqM
  IZEnF4Y5LBzjksHXR+QyDnnYuzN25JEZU+VCRNeEwT4iLCBnYxmOHRWROxo4PVIh
  vtRvbqjHk2XP7CdgC1UFN2fQT3586J9RbOWLNGWiHWC3DfZyMVVCQL3w3UdqK8zf
  ZDqVcV1S9UR6p4rtQOCmVADr1Y4=
  -----END CERTIFICATE-----

catalog_next_saml2_sp_private_key: "{{ vault_catalog_next_saml2_sp_private_key }}"


# common
common_audit_report_enabled: false
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_python_version_number: 2.7.10
# Trailing space is signficant here.
common_shell_prompt: >-
  ${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\] (production) \[\033[01;34m\]\w\[\033[00m\]\$ 
common_ubuntu_advantage_token: "{{ vault_common_ubuntu_advantage_token }}"
filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix these with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: labs.data.gov $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://labs.data.gov/dashboard
php_cli_memory_limit: 3192M

# data.gov-wide variables
datagov_environment: production


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
-----BEGIN CERTIFICATE-----
MIIMDTCCCvWgAwIBAgIQAo1E9z5YnDHoLj5Pu4XiOTANBgkqhkiG9w0BAQsFADBP
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSkwJwYDVQQDEyBE
aWdpQ2VydCBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTAeFw0yMTAyMDEwMDAwMDBa
Fw0yMjAxMzAyMzU5NTlaMH4xCzAJBgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmlj
dCBvZiBDb2x1bWJpYTETMBEGA1UEBxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2Vu
ZXJhbCBTZXJ2aWNlcyBBZG1pbmlzdHJhdGlvbjERMA8GA1UEAxMIZGF0YS5nb3Yw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDaNs2Zu3mzvrC4XLScQtX6
BcmWB9zL+f0AWnB39AZsj8Fhnnjl4ycrtUv3qK/m+gEjTj9ky6dhukKL0BdpDyug
cfvChAHUy/gXhtAgxt4t46EtV/1ofpHLQnVNOkGHjkOIGJGBqULluthsZ1JYHSGe
0by7jLYzvwnOK+g9rjO8jupWV2O9HiNuhmjjHGkvx+haTSA2rkq8CKlMXSL2dPla
/7WXnbuh9rAtce12Zk2yj0tm2+kPLuuyZwslp06Gk2M+rEXKueXx9lR71MUlr5Bn
ez7s187/ImsbYLClMGxztcaktx7y29Dn5ktYZZZJaSiPBcbrg4U54AogUxtxfC3h
AgMBAAGjggi0MIIIsDAfBgNVHSMEGDAWgBS3a6LqqKqEjHnqtNoPmLLFlXa59DAd
BgNVHQ4EFgQUfywGnGApZc1Y2WSS3HeD1Q9rOkcwggXYBgNVHREEggXPMIIFy4II
ZGF0YS5nb3aCDWFhcGkuZGF0YS5nb3aCFmFkbWluLWNhdGFsb2cuZGF0YS5nb3aC
GmFkbWluLWNhdGFsb2ctYnNwLmRhdGEuZ292ghthZG1pbi1jYXRhbG9nLW5leHQu
ZGF0YS5nb3aCC2FnLmRhdGEuZ292ghRhZ3JpY3VsdHVyZS5kYXRhLmdvdoIOYWxw
aGEuZGF0YS5nb3aCEmJ1c2luZXNzcy5kYXRhLmdvdoIUYnVzaW5lc3N1c2EuZGF0
YS5nb3aCEGNhdGFsb2cuZGF0YS5nb3aCFGNhdGFsb2ctYnNwLmRhdGEuZ292ghVj
YXRhbG9nLW5leHQuZGF0YS5nb3aCC2NpLmRhdGEuZ292gg9jaXRpZXMuZGF0YS5n
b3aCEGNsaW1hdGUuZGF0YS5nb3aCEWNvbnN1bWVyLmRhdGEuZ292ghJjb25zdW1l
cnMuZGF0YS5nb3aCG2Nvb3Auc21hbGxidXNpbmVzcy5kYXRhLmdvdoIRY291bnRp
ZXMuZGF0YS5nb3aCFmRhc2hib2FyZC1ic3AuZGF0YS5nb3aCF2Rhc2hib2FyZC1s
YWJzLmRhdGEuZ292ghJkZXZlbG9wZXIuZGF0YS5nb3aCEWRpc2FzdGVyLmRhdGEu
Z292ghJkaXNhc3RlcnMuZGF0YS5nb3aCE2Vjb3N5c3RlbXMuZGF0YS5nb3aCC2Vk
LmRhdGEuZ292ghJlZHVjYXRpb24uZGF0YS5nb3aCD2VuZXJneS5kYXRhLmdvdoIP
ZXRoaWNzLmRhdGEuZ292ghBleHBsb3JlLmRhdGEuZ292ghJmaWxlc3RvcmUuZGF0
YS5nb3aCEGZpbmFuY2UuZGF0YS5nb3aCDWZvb2QuZGF0YS5nb3aCFWZvb2RzZWN1
cml0eS5kYXRhLmdvdoITZ2Vvc3BhdGlhbC5kYXRhLmdvdoIaZ2xvYmFsZGV2ZWxv
cG1lbnQuZGF0YS5nb3aCD2hlYWx0aC5kYXRhLmdvdoITaGlnaGxpZ2h0cy5kYXRh
LmdvdoIUaHVtYW5yaWdodHMuZGF0YS5nb3aCEmludmVudG9yeS5kYXRhLmdvdoIW
aW52ZW50b3J5LWJzcC5kYXRhLmdvdoIXaW52ZW50b3J5LW5leHQuZGF0YS5nb3aC
DWpvYnMuZGF0YS5nb3aCDWxhYnMuZGF0YS5nb3aCEWxhYnMtYnNwLmRhdGEuZ292
ggxsYXcuZGF0YS5nb3aCDW1ha2UuZGF0YS5nb3aCD21hbmFnZS5kYXRhLmdvdoIW
bWFudWZhY3R1cmluZy5kYXRhLmdvdoINbmV4dC5kYXRhLmdvdoIPbm90aWNlLmRh
dGEuZ292ghJudXRyaXRpb24uZGF0YS5nb3aCDm9jZWFuLmRhdGEuZ292ghNvcGVu
c291cmNlLmRhdGEuZ292ghlvcmlnaW5zLWRhdGEtZ292LmRhdGEuZ292gh5vcmln
aW5zLXNtYWxsYnVzaW5lc3MuZGF0YS5nb3aCEnJlZmVyZW5jZS5kYXRhLmdvdoIR
cmVzZWFyY2guZGF0YS5nb3aCDnJ1cmFsLmRhdGEuZ292gg9zYWZldHkuZGF0YS5n
b3aCDHNieC5kYXRhLmdvdoIQc2NpZW5jZS5kYXRhLmdvdoIPc2VhcmNoLmRhdGEu
Z292ghFzZW1hbnRpYy5kYXRhLmdvdoIRc2VydmljZXMuZGF0YS5nb3aCE3NpdGVz
LW5leHQuZGF0YS5nb3aCD3NraWxscy5kYXRhLmdvdoIWc21hbGxidXNpbmVzcy5k
YXRhLmdvdoIYc21hcnRkaXNjbG9zdXJlLmRhdGEuZ292gg9zdGF0ZXMuZGF0YS5n
b3aCFHN1cHBseWNoYWluLmRhdGEuZ292gg52b2NhYi5kYXRhLmdvdoIQd2VhdGhl
ci5kYXRhLmdvdoIPd3AtYnNwLmRhdGEuZ292ggx3d3cuZGF0YS5nb3YwDgYDVR0P
AQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjCBiwYDVR0f
BIGDMIGAMD6gPKA6hjhodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRU
TFNSU0FTSEEyNTYyMDIwQ0ExLmNybDA+oDygOoY4aHR0cDovL2NybDQuZGlnaWNl
cnQuY29tL0RpZ2lDZXJ0VExTUlNBU0hBMjU2MjAyMENBMS5jcmwwPgYDVR0gBDcw
NTAzBgZngQwBAgIwKTAnBggrBgEFBQcCARYbaHR0cDovL3d3dy5kaWdpY2VydC5j
b20vQ1BTMH0GCCsGAQUFBwEBBHEwbzAkBggrBgEFBQcwAYYYaHR0cDovL29jc3Au
ZGlnaWNlcnQuY29tMEcGCCsGAQUFBzAChjtodHRwOi8vY2FjZXJ0cy5kaWdpY2Vy
dC5jb20vRGlnaUNlcnRUTFNSU0FTSEEyNTYyMDIwQ0ExLmNydDAMBgNVHRMBAf8E
AjAAMIIBBgYKKwYBBAHWeQIEAgSB9wSB9ADyAHcAKXm+8J45OSHwVnOfY6V35b5X
fZxgCvj5TV0mXCVdx4QAAAF3XrAmwwAABAMASDBGAiEA80Aw8sqNqCeN/eBpM+zn
LkZbEBZPCAS7rIgFG/ucRMECIQDU9Lftzc2pOuo+7M77DnejlTjk30A4VYtHtmHk
ZNoOOgB3ACJFRQdZVSRWlj+hL/H3bYbgIyZjrcBLf13Gg1xu4g8CAAABd16wJwYA
AAQDAEgwRgIhAJwm8zDqIqts/YafbrP01bKQlWjYpTNzXEkzOPNGrcOiAiEAs1ag
AP0qGL3qLJH4d4z11hfCQXnwKMfDgB1ervGes5kwDQYJKoZIhvcNAQELBQADggEB
AL4Bo/wOZcpELRtI5PBmoLONkJh+n1lZct2cxEf80E/+nP0jH+qDF02Z2OSsHH7L
P3YVYj5hHNtcSRthhwQABwt4KhgJpEAAG+lTnxvmdyh979HUi9teeP2kcVKelJdc
hwhaJZeEQSg+s1JkoKhPYqn2NF52199nWZjFTNftCYEfZ/2O9HRGOhGuaiS4D9a5
/Wt/38alnW6jUis9NS0DI10lhSl13UxsnKvCanrF7j0Mba5E8hJp+qa7bOPhIZue
QVP2pjFScvYi4UaUQd1HKEYydERhTFFuktpEKBVxkqmrbQSM+Za1VhD1yWFY7Po0
ItZia0uIGsEtFJZCHA4wryg=
-----END CERTIFICATE-----

jumpbox_operators: "{{ datagov_operators_production }}"
jumpbox_shell_prompt: "{{ common_shell_prompt }}"


inventory_ckan_service_url: https://inventory.data.gov
inventory_ckan_solr_host: datagov-solrm1p.prod-ocsit.bsp.gsa.gov
inventory_ckan_solr_port: "8983"
inventory_ckan_who_ini_path: "etc_ckan_who.saml2.ini.j2"

# Inventory Next
inventory_next_ckan_envs: |
  {{ newrelic_app_envs }}
inventory_next_ckan_redis_host: "redis1p.prod-ocsit.bsp.gsa.gov"
inventory_next_ckan_redis_password: "{{ redis_password }}"
inventory_next_ckan_s3_bucket_name: "{{ vault_inventory_next_ckan_s3_bucket_name }}"
inventory_next_ckan_s3_bucket_prefix: "{{ vault_inventory_next_ckan_s3_bucket_prefix }}"
inventory_next_ckan_instance_secret: "{{ vault_inventory_next_ckan_instance_secret }}"
inventory_next_ckan_instance_uuid: "{{ vault_inventory_next_ckan_instance_uuid }}"
inventory_next_ckan_service_url: https://inventory.data.gov
inventory_next_ckan_solr_host: datagov-solrm1p-v2.prod-ocsit.bsp.gsa.gov
inventory_next_ckan_who_ini_secret: "{{ vault_inventory_next_ckan_who_ini_secret }}"
inventory_next_datastore_login_host: "{{ vault_inventory_next_datastore_login_host }}"
inventory_next_datastore_db_name: "{{ vault_inventory_next_datastore_db_name }}"
inventory_next_datastore_user: "{{ vault_inventory_next_datastore_user }}"
inventory_next_datastore_pass: "{{ vault_inventory_next_datastore_pass }}"
inventory_next_datastore_ro_user: "{{vault_inventory_next_datastore_ro_user }}"
inventory_next_datastore_ro_pass: "{{ vault_inventory_next_datastore_ro_pass }}"
inventory_next_postgresql_login_host: "{{ vault_inventory_next_postgresql_login_host }}"
inventory_next_postgresql_login_user: "{{ vault_inventory_next_postgresql_login_user }}"
inventory_next_postgresql_login_password: "{{ vault_inventory_next_postgresql_login_password }}"
inventory_next_postgresql_db_name: "{{ vault_inventory_next_postgresql_db_name }}"
inventory_next_datapusher_db_name: "{{ vault_inventory_next_datapusher_db_name }}"

# New Relic
newrelic_enabled: true
newrelic_license_key: "{{ vault_newrelic_license_key }}"


pycsw_app_version: fcs
pycsw_base_url: https://catalog.data.gov
pycsw_ckan_url: https://catalog.data.gov
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"

# public urls
catalog_host_public: catalog.data.gov
catalog_host_admin: admin-catalog.data.gov

catalog_url_public: https://{{ catalog_host_public }}
catalog_url_admin: https://{{ catalog_host_admin }}

ckan_site_domain: "{{ catalog_host_public }}"

# next public urls
catalog_host_public_next: catalog.data.gov
catalog_host_admin_next: admin-catalog-next.data.gov


# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"


# solr
solr_master_server: datagovsolrm1p.prod-ocsit.bsp.gsa.gov
solr_java_packages:
  - openjdk-8-jdk
solr_cores:
  - catalog
  - inventory
solr_xms: 8192m
solr_xmx: 12288m



# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"

# TrendMicro
trendmicro_deb_url: https://dsm.sec.helix.gsa.gov/software/agent/Ubuntu_14.04/x86_64/
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_jumpbox: "{{ vault_trendmicro_policy_id_jumpbox }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: production

# postfix
default_email_from: no-reply@data.gsa.gov
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
  - |
    # Postfix needs a value set https://github.com/GSA/datagov-deploy/issues/1795
    smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: "@{{ ansible_fqdn }}"
    rewrite: no-reply+{{ ansible_fqdn }}@data.gsa.gov


# Redis
redis_password: "{{ vault_redis_password }}"


# SAML
saml2_idp_entry: login.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"

# td-agent
elasticsearch_endpoint: "{{ vault_elasticsearch_endpoint }}"
bsp_elasticsearch_endpoint: "{{ vault_bsp_elasticsearch_endpoint }}"
bsp_shared_key: "{{ vault_bsp_shared_key }}"
system: "es"

# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"

# saxon license
fgdc2iso_saxon_license: "{{ vault_fgdc2iso_saxon_license }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# Automated CI tests
ci_inventory: inventories/production
ci_ssh_config_host: '*.prod-ocsit.bsp.gsa.gov'
ci_deploy_version: master


# wordpress
# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: www.data.gov data.gov labs.data.gov $hostname {{ ansible_default_ipv4.address }}
wordpress_project_git_version: fcs
wordpress_service_url: https://www.data.gov
