version: 2
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: particlekit/ansible-lint
    working_directory: ~/repo
    steps:
      - run: ansible-lint --version
      - checkout
      - run: |
          pip install --user --upgrade pipenv
          pipenv install --dev
      - run: echo 'password' > ~/ansible-secret.txt
      - run: make lint

  test:
    machine: true
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    parallelism: 4
    steps:
      - checkout
      # Restore cache and install python dependencies
      - restore_cache:
          keys:
            - v1-pipfile-{{ checksum "Pipfile.lock" }}
            - v1-pipfile-
      - run: |
          pip install --user --upgrade pipenv
          pipenv install --dev
      - save_cache:
          key: v1-pipfile-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      # Restore cache and install ruby dependencies
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: |
            TEST_TARGETS=$(make circleci-glob | circleci tests split)
            make ${TEST_TARGETS}


workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test
