version: 2
jobs:
  lint:
    docker:
      # specify the version you desire here
      - image: particlekit/ansible-lint

    working_directory: ~/repo

    steps:
      - run: ansible-lint --version
      - checkout
      - run: echo 'password' > ~/ansible-secret.txt
      - run: make lint

  test-kitchen:
    machine: true
    environment:
      KITCHEN_CONCURRENCY: "4"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: pip install -r requirements.txt
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run test-kitchen
          command: make test

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test-kitchen
