version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pipfile-{{ checksum "Pipfile.lock" }}
            - v1-pipfile-
      - run:
          name: python dependencies
          command: |
            pip install --user --upgrade pipenv
            pipenv install --dev
      - save_cache:
          key: v1-pipfile-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run: echo 'password' > ~/ansible-secret.txt
      - run: make lint

  test:
    machine: true
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    parallelism: 4
    steps:
      - checkout
      - run:
          name: setup path
          command: |
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      # Restore cache and install python dependencies
      - restore_cache:
          keys:
            - v1-pipfile-{{ checksum "Pipfile.lock" }}
            - v1-pipfile-
      - run:
          name: python dependencies
          command: |
            pip install --user --upgrade pipenv
            pipenv install --dev
      - save_cache:
          key: v1-pipfile-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      # Restore cache and install ruby dependencies
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      - run:
          name: ruby dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: tests
          command: |
            TEST_TARGETS=$(make circleci-glob | circleci tests split)
            make ${TEST_TARGETS}


workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test
