---

inventory_next: true
ckan_production_ini_template: inventory-next/etc_ckan_production.ini.j2

inventory_ckan_saml2_enabled: "{{ inventory_next_ckan_saml2_enabled }}"
inventory_ckan_who_ini_path: "{{ inventory_next_ckan_who_ini_path }}"

inventory_ckan_plugins_default:
  - datajson
  - datapusher
  - datastore
  - dcat_usmetadata
  - googleanalyticsbasic
  - recline_view
  - stats
  - text_view
  - usmetadata
  - saml2