---
- name: Install Filebeats logging agent
  hosts: all
  roles:
    - role: gsa.ansible-role-beats
      products:
        - filebeat
      vars:
        filebeat_config:
          filebeat.config.modules:
            enabled: true
            path: ${path.config}/modules.d/*.yml
          filebeat.inputs:
           - paths: [/var/log/auth.log]
             type: log  
          filebeat.modules:
            - module: system
              syslog:
                enabled: true
          output.logstash:
            hosts: ["{{ vault.secops_logstash_output }}"]
