---
common_python_version_number: 2.7.16

datagov_service: catalog

# role url
url_readonly: "{{ urls_public.catalog }}"
url_writable: https://catalog.bionic.datagov.us

# project path
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
project_index_path: /usr/lib/ckan

# other
catalog_ckan_redis_host: catalog-harvester1tf.internal.bionic.datagov.us
catalog_ckan_solr_host: datagovsolr1tf.internal.bionic.datagov.us
env: local
redis_password: "{{ vault_redis_pass }}"

# max login
saml2_site_url: https://catalog.bionic.datagov.us

# secrets
who_ini_secret: "{{ vault_who_ini_secret }}"
ckan_instance_secret: "{{ vault_ckan_instance_secret }}"
ckan_instance_uuid: "{{ vault_ckan_instance_secret }}"

# token_dat for Google Analytics
token_dat : "{{ vault_token_dat }}"

