---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - roles/infrastructure/common/vars/main.yml
    - roles/infrastructure/inventory/vars/main.yml
    - roles/infrastructure/inventory/vars/elb.yml
    - roles/infrastructure/inventory/vars/lc.yml
    - roles/infrastructure/inventory/vars/asg.yml
    - roles/infrastructure/inventory/vars/subnet.yml
    - roles/infrastructure/inventory/vars/rds.yml
    - roles/infrastructure/inventory/vars/route53.yml
    - group_vars/ckan-server/vars.yml
    - group_vars/ckan-server/vault.yml

  tasks:
    - include: roles/infrastructure/common/tasks/vpc.yml
    - include: roles/infrastructure/inventory/tasks/subnets.yml
    - include: roles/infrastructure/inventory/tasks/nat.yml
    - include: roles/infrastructure/inventory/tasks/route_tables.yml
    - include: roles/infrastructure/inventory/tasks/sg.yml
    - include: roles/infrastructure/inventory/tasks/rds_subnet_group.yml 
    - include: roles/infrastructure/inventory/tasks/rds.yml 
    - include: roles/infrastructure/inventory/tasks/elb.yml
    - include: roles/infrastructure/inventory/tasks/s3.yml
    - include: roles/infrastructure/inventory/tasks/iam_role.yml
    - include: roles/infrastructure/inventory/tasks/iam_policy.yml
    - include: roles/infrastructure/inventory/tasks/lc.yml
    - include: roles/infrastructure/inventory/tasks/asg.yml
    - include: roles/infrastructure/inventory/tasks/route53.yml
