---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - roles/infrastructure/common/vars/main.yml
    - roles/infrastructure/catalog/vars/main.yml
    - roles/infrastructure/catalog/vars/elb.yml
    - roles/infrastructure/catalog/vars/lc.yml
    - roles/infrastructure/catalog/vars/subnet.yml
    - roles/infrastructure/catalog/vars/rds.yml
    - roles/infrastructure/catalog/vars/route53.yml

  tasks:
    - include: roles/infrastructure/catalog/tasks/route53_delete.yml
    - include: roles/infrastructure/catalog/tasks/rds_delete.yml
    - include: roles/infrastructure/catalog/tasks/rds_subnet_group_delete.yml
    - include: roles/infrastructure/catalog/tasks/elasticache_delete.yml
    - include: roles/infrastructure/catalog/tasks/elasticache_subnet_group_delete.yml
    - include: roles/infrastructure/catalog/tasks/asg_delete.yml
    - include: roles/infrastructure/catalog/tasks/lc_delete.yml
    - include: roles/infrastructure/catalog/tasks/elb_delete.yml
    - include: roles/infrastructure/catalog/tasks/sg_delete.yml
    - include: roles/infrastructure/catalog/tasks/nat_delete.yml
    - include: roles/infrastructure/catalog/tasks/subnets_delete.yml
    - include: roles/infrastructure/catalog/tasks/route_tables_delete.yml
