--- # WordPress Web AMI

#- name: Initial prechecks
#  hosts: wordpress-web
#  remote_user: ubuntu
#
#  roles:
#  - { role: datagov-sudo-0-precheck, tags: [precheck] }

- name: Provisioning WordPress Web AMI
  hosts: {{ playbook_hosts | default('wordpress_web') }}
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
  - { role: misc, tags: [provision, misc] }
  - { role: datagov-sudo-1-security, tags: [provision] }
  - { role: git, tags: [provision] }
  - { role: nginx, tags: [provision] }
  - { role: php, tags: [php, provision] }
  - { role: php-mysql, tags: [php, php-mysql, provision] }
  - { role: php-memcached, tags: [php, php-memcached, provision] }
  - { role: wp-cli, tags: [php, cli, provision] }
  - { role: composer, tags: [php, provision] }
  - { role: vim, tags: [provision, vim] }
  - { role: datagov-sudo-2-init, tags: [provision, deploy, deploy-rollback] }
  - { role: secops-ssh, tags: [provision, secops] }
  - { role: trendmicro, tags: [provision, trendmicro] }
  - { role: ansible-postfix, tags: [provision, postfix] }


- name: Deploying Data.gov
  hosts: wordpress-web
  remote_user: ubuntu

  roles:
  - { role: datagov-deploy, tags: [deploy, provision] }
  - { role: datagov-deploy-rollback, tags: [deploy-rollback] }


- name: Cleanup
  hosts: wordpress-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
  - { role: datagov-sudo-3-cleanup, tags: [provision, deploy, deploy-rollback] }
