---

- name: Install ElasticSearch
  hosts: elasticsearch
  sudo: yes
  remote_user: ubuntu
  roles: 
  - ANXS.apt
  - geerlingguy.java
  - geerlingguy.elasticsearch

- name: Install Kibana
  hosts: kibana
  sudo: yes
  remote_user: ubuntu
  roles: 
  - geerlingguy.kibana

- name: Install EFK nginx proxy
  hosts: efk_nginx
  sudo: yes
  remote_user: ubuntu
  roles: 
  - role: geerlingguy.nginx
  - role: software/common/nginx-fixes
  - role: monitoring/efk-nginx

- name: Install Elastalert
  hosts: elasticsearch 
  sudo: yes
  remote_user: ubuntu
  roles:
    - role: ANXS.build-essential
    - role: teampants.elastalert
    - role: monitoring/elastalert
