---
- name: Install CKAN Stack
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    app_type: inventory

  roles:
    - {role: software/common/misc, tags: ['misc']}
    - software/ubuntu/common
    - {role: software/common/secops-ssh, tags: ['secops']}
    - {role: software/common/trendmicro, tags: ['trendmicro']}
    - {role: software/common/ansible-postfix, tags: ['postfix']}
    - {role: monitoring/fluentd/kernel, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: monitoring/fluentd/limits, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: monitoring/fluentd/td-agent, tags: ['frontend', 'harvester', 'fluentd'] }
    - software/ckan/common
    - software/ckan/apache
    - {role: software/ckan/postgresql, tags: ['db', 'db-install']}
    - {role: software/ckan/solr, tags: ['solr']}
    - {role: software/inventory/ckan-app, tags: ['deploy']}
    - {role: software/ckan/saml2, tags: ['saml2']}
    - software/ckan/security-fix
    - {role: software/inventory/ckan-db-setup, tags: ['db', 'db-setup']}
    - {role: software/inventory/ckan-db-init, tags: ['db', 'db-init']}
    - software/ec2/ec2-inventory
    - {role: software/common/datagov-deploy-rollback, tags: ['deploy-rollback']}
