---
- name: Install CKAN Stack
  hosts: all
  remote_user: ubuntu
  sudo: yes
  vars:
    app_type: inventory

  roles:
    - {role: misc, tags: ['misc']}
    - roles/software/ubuntu/common
    - {role: secops-ssh, tags: ['secops']}
    - {role: trendmicro, tags: ['trendmicro']}
    - {role: ansible-postfix, tags: ['postfix']}
    - {role: roles/monitoring/fluentd/kernel, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: roles/monitoring/fluentd/limits, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: roles/monitoring/fluentd/td-agent, tags: ['frontend', 'harvester', 'fluentd'] }
    - roles/software/ckan/common
    - roles/software/ckan/apache
    - {role: roles/software/ckan/postgresql, tags: ['db', 'db-install']}
    - {role: roles/software/ckan/solr, tags: ['solr']}
    - {role: roles/software/inventory/ckan-app, tags: ['deploy']}
    - {role: roles/software/ckan/saml2, tags: ['saml2']}
    - roles/software/ckan/security-fix
    - roles/software/ckan/apache-headers-fix
    - {role: roles/software/inventory/ckan-db-setup, tags: ['db', 'db-setup']}
    - {role: roles/software/inventory/ckan-db-init, tags: ['db', 'db-init']}
    - ec2-inventory
    - {role: datagov-deploy-rollback, tags: ['deploy-rollback']}
