---
- name: Provisioning Inventory CKAN Stack
  hosts: inventory-next
  serial: "{{ datagov_serial | default(1) }}"

  roles:
    - {role: software/common/tls, tags: ['tls']}
    - software/ckan/common
    - role: gsa.datagov-deploy-apache2
      apache2_enabled: "{{ datagov_in_service | default(true) }}"
      tags: apache
    - {role: software/ckan/inventory, tags: ['deploy']}

  # Host-level smoke tests
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert datapusher is up
      uri:
        url: http://localhost:8800
        follow_redirects: none
        status_code: 200
        validate_certs: false
      retries: 10
      delay: 10
      register: result
      until: not result.failed
      become: false
      when: datagov_in_service | default(true)
      tags:
        - smoke

    - name: assert app is up
      uri:
        url: https://{{ ansible_fqdn }}/api/action/status_show
        follow_redirects: none
        status_code: 200
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
      retries: 10
      delay: 10
      register: result
      until: not result.failed
      when: datagov_in_service | default(true)
      tags:
        - smoke


- name: logrotate configuration
  hosts: inventory-next
  roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: inventory
          paths:
            - /var/log/inventory/*.log
          options:
            - compress
            - copytruncate
            - weekly
            - missingok
            - rotate 8


- name: Service-level smoke tests
  hosts: inventory-next
  tags:
    - smoke
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert inventory service is available
      uri:
        url: "{{ inventory_ckan_service_url }}/api/action/status_show"
        follow_redirects: none
        status_code: 200
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
        headers:
          # Avoid login redirect
          Cookie: auth_tkt=1
      run_once: true
      delegate_to: localhost
      become: false
      retries: 3
      delay: 10
      register: result
      until: not result.failed
