---
- name: Install
  hosts: '{{ playbook_hosts | default('localhost') }}'
  sudo: yes
  vars:
      app_type: jumpbox

  roles:
    - {role: roles/software/ubuntu/common, tags: ['always']}
    - {role: roles/software/ckan/apache, tags: ['jumpbox', 'apache']}

    - {role: roles/security/shibboleth, tags: ['jumpbox', 'shibboleth']}
    - {role: roles/security/shibboleth, tags: ['jumpbox', 'shibboleth']}
