---
- hosts: all # run with --limit catalog-web
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Bring in updated url_for implementation from PR2599
      patch: >
        src={{playbook_dir}}/files/2599_ckan.patch
        basedir=/usr/lib/ckan/src/ckan
        strip=1

    - name: Restart apache2 one more time
      service: name=apache2 state=restarted enabled=yes
