---
- name: Set the deploy version
  hosts: pycsw-web,pycsw-worker,!v2
  tasks:
    - name: Set deploy version
      set_fact:
        pycsw_deploy_version: "{{ '%Y%m%d%H%M%SZ' | strftime(ansible_date_time.epoch) }}"
      run_once: true
  tags: always

- name: CSW web
  hosts: pycsw-web,!v2
  serial: 1
  roles:
    - role: gsa.datagov-deploy-pycsw
      pycsw_role: web
  tags:
    - pycsw
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert csw-collection is up
      uri:
        url: http://{{ ansible_fqdn }}/csw?service=CSW&version=2.0.2&request=GetCapabilities
        follow_redirects: none
        status_code: 200
        return_content: true
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
        headers:
          # For catalog-admin hosts
          Cookie: auth_tkt=1
      register: csw_collection
      retries: 3
      delay: 10
      until: not csw_collection.failed

    - name: assert csw-collection response has title
      fail:
        msg: csw-collection response did not contain ows:Title attribute
      when: csw_collection.content is not search("<ows:Title>CSW interface for catalog.data.gov</ows:Title>")

    - name: assert csw-all is up
      uri:
        url: http://{{ ansible_fqdn }}/csw-all?service=CSW&version=2.0.2&request=GetCapabilities
        follow_redirects: none
        status_code: 200
        return_content: true
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
        headers:
          # For catalog-admin hosts
          Cookie: auth_tkt=1
      register: csw_all
      retries: 3
      delay: 10
      until: not csw_all.failed

    - name: assert csw-all response has title
      fail:
        msg: csw-all response did not contain ows:Title attribute
      when: csw_all.content is not search("<ows:Title>CSW interface for catalog.data.gov</ows:Title>")


- name: CSW worker
  hosts: pycsw-worker,!v2
  roles:
    - role: gsa.datagov-deploy-pycsw
      pycsw_role: worker
  tags:
    - pycsw


- name: Service-level smoke tests
  hosts: pycsw-web,!v2
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert csw-collection is up
      uri:
        url: "{{ catalog_ckan_service_url }}/csw?service=CSW&version=2.0.2&request=GetCapabilities"
        follow_redirects: none
        status_code: 200
        return_content: true
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
      register: csw_collection
      run_once: true
      delegate_to: localhost

    - name: assert csw-collection response has title
      fail:
        msg: csw-collection response did not contain ows:Title attribute
      when: csw_collection.content is not search("<ows:Title>CSW interface for catalog.data.gov</ows:Title>")
      run_once: true
      delegate_to: localhost

    - name: assert csw-all is up
      uri:
        url: "{{ catalog_ckan_service_url }}/csw-all?service=CSW&version=2.0.2&request=GetCapabilities"
        follow_redirects: none
        status_code: 200
        return_content: true
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
      register: csw_all
      run_once: true
      delegate_to: localhost

    - name: assert csw-all response has title
      fail:
        msg: csw-all response did not contain ows:Title attribute
      when: csw_all.content is not search("<ows:Title>CSW interface for catalog.data.gov</ows:Title>")
      run_once: true
      delegate_to: localhost
