---
- name: Install WSGI app
  copy: src=etc_ckan_apache.wsgi dest=/etc/ckan/apache.wsgi mode=0644 owner=root group=www-data
  notify: reload apache2
  when: not ckan_uses_gunicorn

- name: Install supervisor
  apt: name=supervisor state=present

- name: Copy gunicorn supervisord config
  template:
    src: supervisord_gunicorn.conf.j2
    dest: /etc/supervisor/conf.d/supervisord_gunicorn.conf
    mode: 0644
    owner: root
    group: root
  notify: reload supervisor
  when: ckan_uses_gunicorn

- name: Copy mem-cpu-check supervisord config
  copy:
    src: etc/supervisor/conf.d/supervisord_web_mem_cpu.conf
    dest: /etc/supervisor/conf.d/supervisord_web_mem_cpu.conf
    mode: 0644
    owner: root
    group: root
  notify: reload supervisor

- name: copy cpu-mem-check executables
  copy:
    src: usr/bin/cpu-mem-check.sh
    dest: /usr/bin/cpu-mem-check.sh
    mode: 0755
    owner: root
    group: root

- name: Enable supervisor service
  service: name=supervisor state=started enabled=yes

- name: Configure ckan.conf
  template:
    src: etc_apache2_sites-enabled_ckan.conf.j2
    dest: /etc/apache2/sites-enabled/ckan.conf
    mode: 0644
    owner: root
    group: www-data
  notify: reload apache2
