---
datagov_in_service: true
db_is_setup: true
inventory_app_source_path: /tmp/inventory-app
inventory_app_repo: https://github.com/GSA/inventory-app.git
inventory_app_repo_branch: master

# used in  production.ini/ckan_site_url and hosts
ckan_site_domain: https://inventory.data.gov
ckan_virtual_env: "{{virtual_env}}"
datapusher_virtual_env: /usr/lib/datapusher
app_type: inventory

inventory_ckan_plugins_additional: []
inventory_ckan_plugins_default:
  - datajson
  - datapusher
  - datastore
  - dcat_usmetadata
  - googleanalyticsbasic
  - recline_view
  - stats
  - text_view
  - usmetadata

# Use local login by default
inventory_ckan_saml2_enabled: false

inventory_app_environment: production
inventory_log_dir: /var/log/inventory
inventory_ckan_error_log: "{{ inventory_log_dir }}/ckan.error.log"
inventory_ckan_access_log: "{{ inventory_log_dir }}/ckan.access.log"
inventory_datapusher_error_log: "{{ inventory_log_dir }}/datapusher.error.log"
inventory_datapusher_access_log: "{{ inventory_log_dir }}/datapusher.access.log"
inventory_gunicorn_error_log: "{{ inventory_log_dir }}/gunicorn.log"

datapusher_build_pkg_name: datapusher
datapusher_build_pkg_branch: datagov/inventory-classic
datapusher_build_pkg_repo: https://github.com/GSA/datapusher
datapusher_build_pkg_requirements: requirements-freeze.txt
datapusher_next_requirements: requirements.txt

# Enable crons only on specific hosts
crons_enabled: false

# provide some default values to be overwritten later by group vars and host vars...
project_index_path: /usr/lib/ckan
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
ckan_instance_secret: a97df940-4ac1-4357-aac2-156d4f21d300
ckan_instance_uuid: cf305c1a-1672-4451-9cc7-250629d6fdee

datastore_db_server: localhost
inventory_ckan_app_version: inventory
inventory_ckan_bucket_name: bucket
inventory_ckan_bucket_prefix: prefix
inventory_ckan_who_ini_path: etc_ckan_who.default.ini.j2
inventory_ckan_ckanext_saml2_version: max
inventory_ckan_db_host: localhost
inventory_ckan_solr_host: localhost
inventory_ckan_solr_port: 8983
inventory_datapusher_db_name: datapusher
inventory_datapusher_db_user: datapusher
inventory_datastore_db_name: datastore
inventory_datastore_ro_user: ckan_datastore_ro
inventory_datastore_user: ckan_datastore
inventory_db_name: ckan
inventory_db_user: ckan
inventory_python_home: "/usr"

inventory_ckan_redis_db: "1"

inventory_next: false
ckan_production_ini_template: etc/ckan/production.ini

saml2_site_url: https://inventory.data.gov/
saml2_idp_entry: login.test.max.gov
saml2_idp_metadata_url: https://{{ saml2_idp_entry }}/idp/shibboleth

# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: False
