---
- name: make sure packages are installed
  action: apt pkg={{item}} state=installed
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - libapache2-modsecurity

- name: default apache removed
  action: file path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Apache | Enable some required modules
  action: command a2enmod rewrite headers
  tags: common

- name: Apache | Enable Web Application Firewall
  action: command a2enmod security2
  tags:
    - web_application_firewall
    - CM-7
    - SC-7
    - SI-10
