---
- name: restart apache2
  service: name=apache2 state=restarted
  when: datagov_in_service

- name: reload supervisor
  service:
    name: supervisor
    state: restarted
  when: datagov_in_service
  tags:
    - skip_ansible_lint